/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  '/login': {
    /** Sign in into the application */
    post: {
      requestBody: {
        content: {
          'application/json': {
            username?: string;
            /** Format: password */
            password: string;
          };
        };
      };
      responses: {
        /** @description Access token detail */
        201: {
          content: {
            'application/json': components['schemas']['AccessToken'];
          };
        };
        /** @description Invalid login credentials */
        400: {
          content: {
            'application/json': unknown;
          };
        };
        401: components['responses']['ApiKeyInvalidError'];
      };
    };
  };
  '/articles': {
    /** List of all articles */
    get: operations['listArticles'];
    /** Create an article */
    post: operations['createArticle'];
  };
  '/articles/{articleId}': {
    /** Article detail with content and comments */
    get: operations['getArticle'];
    /** Delete article */
    delete: operations['deleteArticle'];
    /** Update article detail */
    patch: operations['updateArticle'];
  };
  '/comments': {
    /** Create comment */
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['Comment'];
        };
      };
      responses: {
        /** @description Detail of the created comment */
        201: {
          content: {
            'application/json': components['schemas']['Comment'];
          };
        };
        401: components['responses']['ApiKeyInvalidError'];
      };
    };
  };
  '/comments/{commentId}/vote/up': {
    /** Upvote comment */
    post: {
      parameters: {
        path: {
          commentId: components['parameters']['commentId'];
        };
      };
      responses: {
        /** @description Updated comment detail */
        201: {
          content: {
            'application/json': components['schemas']['Comment'];
          };
        };
        401: components['responses']['ApiKeyInvalidError'];
      };
    };
  };
  '/comments/{commentId}/vote/down': {
    /** Downvote comment */
    post: {
      parameters: {
        path: {
          commentId: components['parameters']['commentId'];
        };
      };
      responses: {
        /** @description Updated comment detail */
        201: {
          content: {
            'application/json': components['schemas']['Comment'];
          };
        };
        401: components['responses']['ApiKeyInvalidError'];
      };
    };
  };
  '/images': {
    /** Upload an image */
    post: {
      requestBody: {
        content: {
          'multipart/form-data': {
            image?: (string)[];
          };
        };
      };
      responses: {
        /** @description Image uploaded successfully */
        201: {
          content: {
            'application/json': (components['schemas']['ImageInfo'])[];
          };
        };
        401: components['responses']['ApiKeyInvalidError'];
      };
    };
  };
  '/images/{imageId}': {
    /** Download image */
    get: {
      parameters: {
        path: {
          imageId: components['parameters']['imageId'];
        };
      };
      responses: {
        /** @description Image file */
        200: never;
        401: components['responses']['ApiKeyInvalidError'];
      };
    };
    /** Delete image */
    delete: {
      parameters: {
        path: {
          imageId: components['parameters']['imageId'];
        };
      };
      responses: {
        /** @description Image no longer exists */
        204: never;
        401: components['responses']['ApiKeyInvalidError'];
      };
    };
  };
  '/tenants': {
    /** Create tenant */
    post: {
      requestBody: {
        content: {
          'application/json': components['schemas']['Tenant'];
        };
      };
      responses: {
        /** @description Detail of the created tenant */
        201: {
          content: {
            'application/json': components['schemas']['Tenant'];
          };
        };
      };
    };
  };
  '/tenants/{tenantId}': {
    /** Info for a specific tenant */
    get: {
      parameters: {
        path: {
          tenantId: components['parameters']['tenantId'];
        };
      };
      responses: {
        /** @description Tenant detail */
        200: {
          content: {
            'application/json': components['schemas']['Tenant'];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Pagination: {
      /** @description Number of items skipped during pagination */
      offset?: number;
      /** @description Number of items returned */
      limit?: number;
      /** @description Total number of items */
      total?: number;
    };
    ArticleList: {
      pagination?: components['schemas']['Pagination'];
      items?: (components['schemas']['Article'])[];
    };
    Article: {
      /** Format: uuid */
      articleId?: string;
      /** @example Lorem Ipsum */
      title?: string;
      /** @example Lorem Ipsum is simply dummy text of the printing and typesetting industry. */
      perex?: string;
      /** Format: uuid */
      imageId?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      lastUpdatedAt?: string;
    };
    ArticleDetail: components['schemas']['Article'] & {
      /**
       * Format: markdown 
       * @example # Lorem Ipsum
       * **Lorem Ipsum** is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.
       */
      content?: string;
      comments?: readonly (components['schemas']['Comment'])[];
    };
    Comment: {
      /** Format: uuid */
      commentId?: string;
      /** Format: uuid */
      articleId: string;
      /** @example Jan Novak */
      author: string;
      /** @example This article is on point and very inspirational. */
      content: string;
      /** Format: date-time */
      postedAt?: string;
      /** @example 42 */
      score?: number;
    };
    ImageInfo: {
      /** Format: uuid */
      imageId: string;
      /** @example screenshot.png */
      name?: string;
    };
    Tenant: {
      /** Format: uuid */
      tenantId?: string;
      /**
       * Format: uuid 
       * @description API key to be used in the `api-key` header
       */
      apiKey?: string;
      /**
       * @description Human readable name of the tenant 
       * @example Jan Novak
       */
      name?: string;
      /**
       * Format: password 
       * @description Authentication password of the tenant 
       * @example correct horse battery staple
       */
      password?: string;
      /** Format: date-time */
      createdAt?: string;
      /** Format: date-time */
      lastUsedAt?: string;
    };
    AccessToken: {
      /**
       * Format: uuid 
       * @description Use this when requesting authenticated API endpoints
       */
      access_token?: string;
      /**
       * @description Number of seconds before the access_token expires 
       * @example 3600
       */
      expires_in?: number;
      /**
       * @description Token type. Will always be bearer 
       * @example bearer
       */
      token_type?: string;
    };
  };
  responses: {
    /** @description API key is missing or invalid */
    ApiKeyInvalidError: {
      content: {
        'application/json': unknown;
      };
    };
    /** @description Access token is missing or invalid */
    UnauthorizedError: {
      content: {
        'application/json': unknown;
      };
    };
  };
  parameters: {
    /** @description Id of the tenant to retrieve */
    tenantId: string;
    /** @description Id of the image to retrieve */
    imageId: string;
    /** @description Id of an article */
    articleId: string;
    /** @description Id of an comment */
    commentId: string;
    /** @description Number of items to skip during pagination */
    offset?: number;
    /** @description Number of items to return per page. All items are returned if `limit` is omitted. */
    limit?: number;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** List of all articles */
  listArticles: {
    parameters: {
      query: {
        offset?: components['parameters']['offset'];
        limit?: components['parameters']['limit'];
      };
    };
    responses: {
      /** @description Article list */
      200: {
        content: {
          'application/json': (components['schemas']['Article'])[];
        };
      };
      401: components['responses']['ApiKeyInvalidError'];
    };
  };
  /** Create an article */
  createArticle: {
    requestBody: {
      content: {
        'application/json': components['schemas']['ArticleDetail'];
      };
    };
    responses: {
      /** @description Detail of the created article */
      200: {
        content: {
          'application/json': components['schemas']['ArticleDetail'];
        };
      };
      401: components['responses']['ApiKeyInvalidError'];
      403: components['responses']['UnauthorizedError'];
    };
  };
  /** Article detail with content and comments */
  getArticle: {
    parameters: {
      path: {
        articleId: components['parameters']['articleId'];
      };
    };
    responses: {
      /** @description Article detail */
      200: {
        content: {
          'application/json': components['schemas']['ArticleDetail'];
        };
      };
      401: components['responses']['ApiKeyInvalidError'];
    };
  };
  /** Delete article */
  deleteArticle: {
    parameters: {
      path: {
        articleId: components['parameters']['articleId'];
      };
    };
    responses: {
      /** @description Article no longer exists */
      204: never;
      401: components['responses']['ApiKeyInvalidError'];
      403: components['responses']['UnauthorizedError'];
    };
  };
  /** Update article detail */
  updateArticle: {
    parameters: {
      path: {
        articleId: components['parameters']['articleId'];
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ArticleDetail'];
      };
    };
    responses: {
      /** @description Updated article detail */
      200: {
        content: {
          'application/json': components['schemas']['ArticleDetail'];
        };
      };
      401: components['responses']['ApiKeyInvalidError'];
      403: components['responses']['UnauthorizedError'];
    };
  };
}
